### ISSUE TITLE
Visual artifacts.

### ISSUE THREAD

**Issue by 3laws** [dracula/duolingo#2]
## Firefox 125.0.1 (also tested on 124.0.1 and 125.0.1. ), Stylus 1.5.46.

Image card have no icons:
![image](https://github.com/dracula/duolingo/assets/4267075/0d975aec-9cdc-49dd-b848-a2858eb545a5)

Feel like something is missing here:
![image](https://github.com/dracula/duolingo/assets/4267075/c5dfd471-dcdf-40a5-ac46-3fd1f97ade82)

Completely broken layering:
![image](https://github.com/dracula/duolingo/assets/4267075/9b65ca75-1aca-4fa7-964f-45142d92ebb0)

Again, juxtaposed elements:
![image](https://github.com/dracula/duolingo/assets/4267075/2d572224-9629-432c-a10e-f0178b35172f)

**Comment by sonofactgnrd** [comment]
duolingos website had an update so i am working on fixing everything.

**Comment by 3laws** [comment]
Appreciated. I can test any updates you make. Thanks again.

**Comment by sonofactgnrd** [comment]
if you want Duolingo now has a dark mode in there settings.
I also added the updates to the main branch

**Comment by sonofactgnrd** [comment]
I have added the updates to the main branch that should fix those
